name = "isqr"
compatibility_date = "2025-01-24"
main = "build/worker/shim.mjs"
account_id = "e2ecc897eaa02efed7cb3cbc4beca1fa"

[build]
command = "worker-build --release"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KV"
id = "290b2bf074f94331bf272a09e2c6f789"
preview_id = "8ac90315e8874a8ca5fe7fe52b2dc778"
experimental_remote = true

[[routes]]
pattern = "isqr.me/*"
zone_name = "isqr.me"
# pattern = "isqr.me/create"
# zone_name = "isqr.me"